### ISSUE TITLE
etags should be in double quotes

### ISSUE THREAD

**Issue by bewinsnw** [simple-repository/simple-repository-server#2]
minor nit:
https://github.com/simple-repository/simple-repository-server/blob/fe353669c64ca77ef9621d377bb728a13e6c33ae/simple_repository_server/routers/simple.py#L135

See the spec:
https://www.rfc-editor.org/rfc/rfc9110#field.etag

I've literally once, ever, seen this be an issue, with virgin media's web-to-cable-tv caches back in 2001.  But that client just dropped responses with misformatted etags on the floor.

**Comment by pelson** [comment]
Turns out this was a problem with starlette too... recently fixed (https://github.com/encode/starlette/issues/2298#issuecomment-1793391343).

This will be fixed in >v0.5.0 (and >0.5.0 of simple-repository core also)

**Comment by pelson** [comment]
Fixed in v0.6.0. Thanks for the nit - it is always good to improve this stuff.

**Comment by pelson** [comment]
Note that it is also necessary to update `simple-repository` at the same time (to v0.7.0) to have local files have correct etags.
