### ISSUE TITLE
main needs a host argument to allow inbound traffic in docker

### ISSUE THREAD

**Issue by bewinsnw** [simple-repository/simple-repository-server#5]
The same as in simple-repository-browser https://github.com/simple-repository/simple-repository-browser/blob/cd75201db43d8716b4022fda49a67b45660d6d16/simple_repository_browser/__main__.py#L30

... as it stands, simple-repository-server launches uvicorn with its default host argument of 127.0.0.1; when run under docker this means it's only listening to traffic from inside the container.

**Comment by pelson** [comment]
Thanks. Should be fixed by #7. (it'll ship in `>0.5.0`)
